export const units = {
  cup: ['c', 'c.', 'C', 'Cups'],
  gallon: ['gal'],
  ounce: ['oz', 'oz.'],
  pint: ['pt', 'pts', 'pt.'],
  pound: ['lb', 'lb.', 'lbs'],
  quart: ['qt', 'qt.', 'qts'],
  tablespoon: ['tbs', 'tbsp', 'tbspn', 'T', 'T.', 'Tablespoons', 'Tablespoon'],
  teaspoon: ['tsp', 'tspn', 't', 't.'],
  gram: ['g', 'g.'],
  kilogram: ['kg', 'kg.'],
  liter: ['l', 'l.'],
  milligram: ['mg', 'mg.'],
  milliliter: ['ml', 'ml.'],
  package: ['pkg', 'pkgs']
} as { [key: string]: string[] };

export const pluralUnits = {
  cup: ['cups'],
  gallon: ['gallons'],
  ounce: ['ounces'],
  pint: ['pints'],
  pound: ['pounds'],
  quart: ['quarts'],
  tablespoon: ['tablespoons'],
  teaspoon: ['teaspoons'],
  gram: ['grams'],
  kilogram: ['kilograms'],
  liter: ['liters'],
  milligram: ['milligrams'],
  milliliter: ['milliliters'],
  clove: ['cloves'],
  bag: ['bags'],
  box: ['boxes'],
  pinch: ['pinches'],
  can: ['cans'],
  slice: ['slices'],
  large: ['large'],
  whole: ['whole'],
  package: ['packages'],
} as { [key: string]: string[] };
