module.exports = {
  'cup': ['c', 'c.', 'cups'],
  'gallon': ['gal', 'gallons'],
  'ounce': ['oz', 'oz.', 'ounces'],
  'pint': ['pt', 'pts', 'pt.', 'pints'],
  'pound': ['lb', 'lb.', 'lbs', 'pounds'],
  'quart': ['qt', 'qt.', 'qts', 'quarts'],
  'tablespoon': ['tbs', 'tbsp', 'tbspn', 'T', 'T.', 'tablespoons', 'Tablespoons', 'Tablespoon'],
  'teaspoon': ['tsp', 'tspn', 't', 't.', 'teaspoons'],
  'gram': ['g', 'g.', 'grams'],
  'kilogram': ['kg', 'kg.', 'kilograms'],
  'liter': ['l', 'l.', 'liters'],
  'milligram': ['mg', 'mg.', 'milligrams'],
  'milliliter': ['ml', 'ml.', 'milliliters'],
  'large': [],
  'whole': [],
  'clove': [],
  'bag': [],
  'pinch': ['pinches'],
  'can': []
}