export const units = {
  cup: ['c', 'c.', 'cups'],
  gallon: ['gal'],
  ounce: ['oz', 'oz.'],
  pint: ['pt', 'pts', 'pt.'],
  pound: ['lb', 'lb.', 'lbs'],
  quart: ['qt', 'qt.', 'qts'],
  tablespoon: [
    'tbs',
    'tbs.',
    'tbsp',
    'tbsp.',
    'tbspn',
    'tbspn.',
    'Tablespoons',
    'Tablespoon',
  ],
  teaspoon: ['tsp', 'tsp.', 'tspn', 'tspn.'],
  gram: ['g', 'g.'],
  kilogram: ['kg', 'kg.'],
  liter: ['l', 'l.'],
  milligram: ['mg', 'mg.'],
  milliliter: ['ml', 'ml.'],
  package: ['pkg', 'pkg.', 'pkgs'],
  stick: ['sticks'],
} as { [key: string]: string[] };

export const pluralUnits = {
  cup: 'cups',
  gallon: 'gallons',
  ounce: 'ounces',
  pint: 'pints',
  pound: 'pounds',
  quart: 'quarts',
  tablespoon: 'tablespoons',
  teaspoon: 'teaspoons',
  gram: 'grams',
  kilogram: 'kilograms',
  liter: 'liters',
  milligram: 'milligrams',
  milliliter: 'milliliters',
  clove: 'cloves',
  bag: 'bags',
  box: 'boxes',
  pinch: 'pinches',
  can: 'cans',
  slice: 'slices',
} as { [key: string]: string };
