module.exports = {
  'cup': ['c', 'c.', 'cups'],
  'gallon': ['gal', 'gallons'],
  'ounce': ['oz', 'oz.', 'ounces'],
  'pint': ['pt', 'pts', 'pt.'],
  'pound': ['lb', 'lb.', 'lbs'],
  'quart': ['qt', 'qt.', 'qts'],
  'tablespoon': ['tbs', 'tbsp', 'tbspn', 'T', 'T.'],
  'teaspoon': ['tsp', 'tspn', 't', 't.'],
  'gram': ['g', 'g.'],
  'kilogram': ['kg', 'kg.'],
  'liter': ['l', 'l.'],
  'milligram': ['mg', 'mg.'],
  'milliliter': ['ml', 'ml.'],
  'large': [],
  'whole': [],
  'clove': [],
  'bag': [],
  'pinch': ['pinches']
}